imagen agregada en modelo propiedad
JAFleitas/room-rental-app pull request #10
Opened 2022-03-15 22:59 UTC by alibertiux

agregado el atributo imagen de la entidad propiedad, arreglado allowNull mal escrito

2022-03-15 23:24 UTC, JAFleitas requested changes
DataTypes tiene una propiedad que es array para poder agregar más de una imagen en columna image

2022-03-16 00:13 UTC, alibertiux commented
> DataTypes tiene una propiedad que es array para poder agregar más de una imagen en columna image

Agregado data type array para multiples imagenes

2022-03-16 00:24 UTC, blaksleyn approved these changes

2022-03-16 02:17 UTC, facundo9963 submitted a review, later dismissed

2022-03-16 03:28 UTC, JAFleitas approved these changes

2022-03-16 03:45 UTC, blaksleyn approved these changes

2022-03-16 18:35 UTC, blaksleyn approved these changes

2022-03-16 18:54 UTC, JAFleitas approved these changes

2022-03-16 22:16 UTC, facundo9963 approved these changes

2022-03-16 22:29 UTC, merged