creando modelo type_user y modificando pk y fk a UUID
JAFleitas/room-rental-app pull request #7
Opened 2022-03-15 22:07 UTC by Overlord41

Acéptenme el pull

2022-03-15 22:10 UTC, alibertiux submitted a review, later dismissed

2022-03-15 22:12 UTC, blaksleyn submitted a review, later dismissed

2022-03-15 23:01 UTC, JAFleitas requested changes
En type_user cambia nombre por name, estamos escribiendo todo en inglés

2022-03-15 23:38 UTC, blaksleyn approved these changes

2022-03-15 23:45 UTC, JAFleitas approved these changes

2022-03-16 02:15 UTC, facundo9963 approved these changes

2022-03-16 02:16 UTC, merged